version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "54003:5000"
    volumes:
      - ./src/Repository:/mnt/Repository
      - ./src/Front-End:/app/Front-End
      - ./src/Databases:/app/Databases
    env_file:
      - .dockerenv
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
