version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "54003:5000"
    volumes:
      - ./Repository:/mnt/Repository
    environment:
      - RUN_MIGRATIONS=$RUN_MIGRATIONS
    env_file:
      - .env
      - secret.env
    depends_on:
      - db
      - redis
    entrypoint: ["/entrypoint.sh"]

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
