version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "54003:5000"
    volumes:
      - ./Repository:/mnt/Repository
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["/entrypoint.sh"]
    command: ["gunicorn", "-b", ":5000", "manage:app"]

  migrate:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./Repository:/mnt/Repository
    entrypoint: ["/entrypoint.sh"]
    command: ["flask", "db", "upgrade"]

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
